name: pawpoints
description: Eine App fÃ¼r Aufgaben und Belohnungssysteme fÃ¼r Doggys ðŸ¶ und Herrchen ðŸ§

publish_to: 'none' # Dieses Projekt soll nicht im pub.dev verÃ¶ffentlicht werden

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  uuid: ^4.0.0


  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0

  # Sonstiges
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: 0.20.2
  qr_flutter: ^4.0.0

  # UI / Material
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
